# Makefile.in generated by automake 1.13.4 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# ***************************************************************************
# Makefile for Hercules S/370, ESA/390 and z/Architecture emulator
# Process this file with 'automake' to produce Makefile.in
#
# $Id$
#
# ***************************************************************************




am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/hercules
pkgincludedir = $(includedir)/hercules
pkglibdir = $(libdir)/hercules
pkglibexecdir = $(libexecdir)/hercules
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
target_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = hercules$(EXEEXT) dasdinit$(EXEEXT) dasdisup$(EXEEXT) \
	zdasdload$(EXEEXT) dasdload$(EXEEXT) dasdconv$(EXEEXT) dasdls$(EXEEXT) \
	dasdcat$(EXEEXT) dasdpdsu$(EXEEXT) dasdseq$(EXEEXT) \
	tapecopy$(EXEEXT) tapemap$(EXEEXT) tapesplt$(EXEEXT) \
	cckdcdsk$(EXEEXT) cckdcomp$(EXEEXT) cckddiag$(EXEEXT) \
	cckdswap$(EXEEXT) dasdcopy$(EXEEXT) hetget$(EXEEXT) \
	hetinit$(EXEEXT) hetmap$(EXEEXT) hetupd$(EXEEXT) \
	dmap2hrc$(EXEEXT) vmfplc2$(EXEEXT) $(am__EXEEXT_1) \
	$(am__EXEEXT_2)
EXTRA_PROGRAMS = hercifc$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in $(top_srcdir)/autoconf/mkinstalldirs \
	$(top_srcdir)/autoconf/depcomp \
	$(top_srcdir)/autoconf/ltmain.sh \
	$(top_srcdir)/autoconf/config.guess \
	$(top_srcdir)/autoconf/config.sub $(noinst_HEADERS) INSTALL \
	autoconf/README autoconf/config.guess autoconf/config.rpath \
	autoconf/config.sub autoconf/depcomp autoconf/install-sh \
	autoconf/missing autoconf/mkinstalldirs autoconf/ltmain.sh \
	$(top_srcdir)/autoconf/install-sh \
	$(top_srcdir)/autoconf/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/autoconf/hercules.m4 \
	$(top_srcdir)/autoconf/libtool.m4 \
	$(top_srcdir)/autoconf/ltdl.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/autoconf/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(modexecdir)" \
	"$(DESTDIR)$(bindir)"
LTLIBRARIES = $(lib_LTLIBRARIES) $(modexec_LTLIBRARIES) \
	$(noinst_LTLIBRARIES)
am__DEPENDENCIES_1 =
am__DEPENDENCIES_2 = libherc.la libhercs.la \
	libhercu.la $(am__DEPENDENCIES_1)
dyn75_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__dyn75_la_SOURCES_DIST = dyn75.c tcpip.c
am_dyn75_la_OBJECTS = dyn75.lo
dyn75_la_OBJECTS = $(am_dyn75_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
dyn75_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dyngui_la_LDFLAGS) $(LDFLAGS) -g $@
am_dyngui_la_rpath = -rpath $(modexecdir)
dyngui_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__dyngui_la_SOURCES_DIST = dyngui.c
am_dyngui_la_OBJECTS = dyngui.lo
dyngui_la_OBJECTS = $(am_dyngui_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
dyngui_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dyngui_la_LDFLAGS) $(LDFLAGS) -o $@
am_dyngui_la_rpath = -rpath $(modexecdir)
dyninst_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__dyninst_la_SOURCES_DIST = dyninst.c
am_dyninst_la_OBJECTS = dyninst.lo
dyninst_la_OBJECTS = $(am_dyninst_la_OBJECTS)
dyninst_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dyninst_la_LDFLAGS) $(LDFLAGS) -o $@
am_dyninst_la_rpath = -rpath $(modexecdir)
dyn75_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__dyn75_la_SOURCES_DIST = dyn75.c tcpip.c
am_dyn75_la_OBJECTS = dyn75.lo
dyn75_la_OBJECTS = $(am_dyn75_la_OBJECTS)
dyn75_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dyn75_la_LDFLAGS) $(LDFLAGS) -o $@
am_dyn75_la_rpath = -rpath $(modexecdir)
hdt1052c_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt1052c_la_SOURCES_DIST = con1052c.c
am_hdt1052c_la_OBJECTS = con1052c.lo
hdt1052c_la_OBJECTS = $(am_hdt1052c_la_OBJECTS)
hdt1052c_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt1052c_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt1052c_la_rpath = -rpath $(modexecdir)
hdt1403_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt1403_la_SOURCES_DIST = printer.c sockdev.c
am_hdt1403_la_OBJECTS = printer.lo \
	sockdev.lo
hdt1403_la_OBJECTS = $(am_hdt1403_la_OBJECTS)
hdt1403_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt1403_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt1403_la_rpath = -rpath $(modexecdir)
hdt2703_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt2703_la_SOURCES_DIST = commadpt.c
am_hdt2703_la_OBJECTS = commadpt.lo
hdt2703_la_OBJECTS = $(am_hdt2703_la_OBJECTS)
hdt2703_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt2703_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt2703_la_rpath = -rpath $(modexecdir)
hdt2880_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt2880_la_SOURCES_DIST = hchan.c
am_hdt2880_la_OBJECTS = hchan.lo
hdt2880_la_OBJECTS = $(am_hdt2880_la_OBJECTS)
hdt2880_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt2880_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt2880_la_rpath = -rpath $(modexecdir)
hdt3088_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt3088_la_SOURCES_DIST = ctc_lcs.c ctc_ctci.c ctcadpt.c w32ctca.c \
	tuntap.c
am_hdt3088_la_OBJECTS = ctc_lcs.lo \
	ctc_ctci.lo ctcadpt.lo w32ctca.lo \
	tuntap.lo
hdt3088_la_OBJECTS = $(am_hdt3088_la_OBJECTS)
hdt3088_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt3088_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt3088_la_rpath = -rpath $(modexecdir)
hdt3270_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt3270_la_SOURCES_DIST = console.c
am_hdt3270_la_OBJECTS = console.lo
hdt3270_la_OBJECTS = $(am_hdt3270_la_OBJECTS)
hdt3270_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt3270_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt3270_la_rpath = -rpath $(modexecdir)
hdt3420_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2) libherct.la
am__hdt3420_la_SOURCES_DIST = tapedev.c tapeccws.c awstape.c \
	faketape.c hettape.c omatape.c scsitape.c w32stape.c
am_hdt3420_la_OBJECTS = tapedev.lo \
	tapeccws.lo awstape.lo faketape.lo \
	hettape.lo omatape.lo scsitape.lo \
	w32stape.lo
hdt3420_la_OBJECTS = $(am_hdt3420_la_OBJECTS)
hdt3420_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt3420_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt3420_la_rpath = -rpath $(modexecdir)
hdt3505_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt3505_la_SOURCES_DIST = cardrdr.c sockdev.c
am_hdt3505_la_OBJECTS = cardrdr.lo \
	sockdev.lo
hdt3505_la_OBJECTS = $(am_hdt3505_la_OBJECTS)
hdt3505_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt3505_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt3505_la_rpath = -rpath $(modexecdir)
hdt3525_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt3525_la_SOURCES_DIST = cardpch.c
am_hdt3525_la_OBJECTS = cardpch.lo
hdt3525_la_OBJECTS = $(am_hdt3525_la_OBJECTS)
hdt3525_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt3525_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt3525_la_rpath = -rpath $(modexecdir)
hdt3705_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdt3705_la_SOURCES_DIST = comm3705.c
am_hdt3705_la_OBJECTS = comm3705.lo
hdt3705_la_OBJECTS = $(am_hdt3705_la_OBJECTS)
hdt3705_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdt3705_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdt3705_la_rpath = -rpath $(modexecdir)
hdteq_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdteq_la_SOURCES_DIST = hdteq.c
am_hdteq_la_OBJECTS = hdteq.lo
hdteq_la_OBJECTS = $(am_hdteq_la_OBJECTS)
hdteq_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdteq_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdteq_la_rpath = -rpath $(modexecdir)
hdtptp_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdtptp_la_SOURCES_DIST = ctc_ptp.c mpc.c resolve.c w32ctca.c \
	tuntap.c
am_hdtptp_la_OBJECTS = ctc_ptp.lo mpc.lo \
	resolve.lo w32ctca.lo tuntap.lo
hdtptp_la_OBJECTS = $(am_hdtptp_la_OBJECTS)
hdtptp_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdtptp_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdtptp_la_rpath = -rpath $(modexecdir)
hdtqeth_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdtqeth_la_SOURCES_DIST = qeth.c mpc.c tuntap.c
am_hdtqeth_la_OBJECTS = qeth.lo mpc.lo \
	tuntap.lo
hdtqeth_la_OBJECTS = $(am_hdtqeth_la_OBJECTS)
hdtqeth_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdtqeth_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdtqeth_la_rpath = -rpath $(modexecdir)
hdtzfcp_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__hdtzfcp_la_SOURCES_DIST = zfcp.c
am_hdtzfcp_la_OBJECTS = zfcp.lo
hdtzfcp_la_OBJECTS = $(am_hdtzfcp_la_OBJECTS)
hdtzfcp_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hdtzfcp_la_LDFLAGS) $(LDFLAGS) -o $@
am_hdtzfcp_la_rpath = -rpath $(modexecdir)
libherc_la_DEPENDENCIES = libhercs.la libhercu.la libherct.la \
	libhercd.la decNumber/libdecNumber.la $(am__DEPENDENCIES_1)
am__libherc_la_SOURCES_DIST = hconsole.c w32util.c strsignal.c impl.c \
	config.c bldcfg.c script.c archlvl.c panel.c history.c  \
	fillfnam.c ipl.c assist.c dat.c stack.c cpu.c vstore.c \
	general1.c general2.c general3.c pfpo.c plo.c control.c \
	crypto.c io.c decimal.c service.c scedasd.c scescsi.c losc.c \
	chsc.c opcode.c diagnose.c diagmssf.c vm.c vmd250.c hdiagf18.c \
	dyn75.c dyn76.c tcpip.c channel.c external.c float.c trace.c machchk.c \
	vector.c xstore.c cmpsc.c sie.c qdio.c clock.c timer.c esame.c \
	ieee.c SoftFloat.c dfp.c machdep.h httpserv.c cgibin.c \
	loadmem.c loadparm.c hsccmd.c hscemode.c hscpufun.c hscloc.c \
	cmdtab.c hao.c hscmisc.c sr.c w32chan.c commadpt.c comm3705.c \
	console.c cardpch.c cardrdr.c sockdev.c printer.c tapedev.c \
	tapeccws.c sllib.c hetlib.c ftlib.c awstape.c faketape.c \
	hettape.c omatape.c scsitape.c w32stape.c ctc_ptp.c ctc_lcs.c \
	ctc_ctci.c ctcadpt.c w32ctca.c hchan.c tuntap.c resolve.c \
	qeth.c mpc.c zfcp.c con1052c.c ecpsvm.c hRexx.c hRexx_o.c \
	hRexx_r.c
am__objects_1 = w32chan.lo
#am__objects_2 = $(am__objects_1)
am__objects_3 = commadpt.lo comm3705.lo console.lo cardpch.lo \
	cardrdr.lo sockdev.lo printer.lo tapedev.lo tapeccws.lo \
	sllib.lo hetlib.lo ftlib.lo awstape.lo faketape.lo hettape.lo \
	omatape.lo scsitape.lo w32stape.lo ctc_ptp.lo ctc_lcs.lo \
	ctc_ctci.lo ctcadpt.lo w32ctca.lo hchan.lo tuntap.lo \
	resolve.lo qeth.lo mpc.lo zfcp.lo con1052c.lo
#am__objects_4 = $(am__objects_3)
am_libherc_la_OBJECTS = hconsole.lo w32util.lo strsignal.lo impl.lo \
	config.lo bldcfg.lo script.lo archlvl.lo panel.lo history.lo \
	fillfnam.lo ipl.lo assist.lo dat.lo stack.lo cpu.lo vstore.lo \
	general1.lo general2.lo general3.lo pfpo.lo plo.lo control.lo \
	crypto.lo io.lo decimal.lo service.lo scedasd.lo scescsi.lo \
	losc.lo chsc.lo opcode.lo diagnose.lo diagmssf.lo vm.lo \
	vmd250.lo hdiagf18.lo dyn75.lo dyn76.lo tcpip.lo\
        channel.lo external.lo float.lo \
	trace.lo machchk.lo vector.lo xstore.lo cmpsc.lo sie.lo \
	qdio.lo clock.lo timer.lo esame.lo ieee.lo SoftFloat.lo dfp.lo \
	httpserv.lo cgibin.lo loadmem.lo loadparm.lo hsccmd.lo \
	hscemode.lo hscpufun.lo hscloc.lo cmdtab.lo hao.lo hscmisc.lo \
	sr.lo $(am__objects_2) $(am__objects_4) ecpsvm.lo hRexx.lo \
	hRexx_o.lo hRexx_r.lo
libherc_la_OBJECTS = $(am_libherc_la_OBJECTS)
libherc_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libherc_la_LDFLAGS) $(LDFLAGS) -o $@
libhercd_la_DEPENDENCIES = $(am__DEPENDENCIES_1) libhercs.la \
	libhercu.la
am_libhercd_la_OBJECTS = ckddasd.lo fbadasd.lo cckddasd.lo cckdutil.lo \
	dasdtab.lo cache.lo dasdutil.lo shared.lo
libhercd_la_OBJECTS = $(am_libhercd_la_OBJECTS)
libhercd_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libhercd_la_LDFLAGS) $(LDFLAGS) -o $@
libhercs_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
am_libhercs_la_OBJECTS = hsys.lo
libhercs_la_OBJECTS = $(am_libhercs_la_OBJECTS)
libhercs_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libhercs_la_LDFLAGS) $(LDFLAGS) -o $@
libherct_la_DEPENDENCIES = $(am__DEPENDENCIES_1) libhercs.la \
	libhercu.la
am_libherct_la_OBJECTS = sllib.lo ftlib.lo hetlib.lo
libherct_la_OBJECTS = $(am_libherct_la_OBJECTS)
libherct_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libherct_la_LDFLAGS) $(LDFLAGS) -o $@
libhercu_la_DEPENDENCIES = $(am__DEPENDENCIES_1) libhercs.la
am__libhercu_la_SOURCES_DIST = version.c hscutl.c hscutl2.c codepage.c \
	logger.c logmsg.c hdl.c hostinfo.c hsocket.c memrchr.c \
	parser.c pttrace.c fthreads.c ltdl.c
am__objects_5 = fthreads.lo
#am__objects_6 = $(am__objects_5)
am__objects_7 = ltdl.lo
am_libhercu_la_OBJECTS = version.lo hscutl.lo hscutl2.lo codepage.lo \
	logger.lo logmsg.lo hdl.lo hostinfo.lo hsocket.lo memrchr.lo \
	parser.lo pttrace.lo $(am__objects_6) $(am__objects_7)
libhercu_la_OBJECTS = $(am_libhercu_la_OBJECTS)
libhercu_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libhercu_la_LDFLAGS) $(LDFLAGS) -o $@
s37x_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_2)
am__s37x_la_SOURCES_DIST = s37x.c s37xmod.c
am_s37x_la_OBJECTS = s37x.lo s37xmod.lo
s37x_la_OBJECTS = $(am_s37x_la_OBJECTS)
s37x_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(s37x_la_LDFLAGS) $(LDFLAGS) -o $@
am_s37x_la_rpath = -rpath $(modexecdir)
am__EXEEXT_1 = hercifc$(EXEEXT)
am__EXEEXT_2 = herclin$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)
am_cckdcdsk_OBJECTS = cckdcdsk.$(OBJEXT)
cckdcdsk_OBJECTS = $(am_cckdcdsk_OBJECTS)
#am__DEPENDENCIES_3 = $(HERCLIBS2) \
#	$(am__DEPENDENCIES_1) hdlmain.o
am__DEPENDENCIES_3 = $(HERCLIBS2) \
	$(am__DEPENDENCIES_1)
cckdcdsk_DEPENDENCIES = $(am__DEPENDENCIES_3)
cckdcdsk_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(cckdcdsk_LDFLAGS) $(LDFLAGS) -o $@
am_cckdcomp_OBJECTS = cckdcomp.$(OBJEXT)
cckdcomp_OBJECTS = $(am_cckdcomp_OBJECTS)
cckdcomp_DEPENDENCIES = $(am__DEPENDENCIES_3)
cckdcomp_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(cckdcomp_LDFLAGS) $(LDFLAGS) -o $@
am_cckddiag_OBJECTS = cckddiag.$(OBJEXT)
cckddiag_OBJECTS = $(am_cckddiag_OBJECTS)
cckddiag_DEPENDENCIES = $(am__DEPENDENCIES_3)
cckddiag_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(cckddiag_LDFLAGS) $(LDFLAGS) -o $@
am_cckdswap_OBJECTS = cckdswap.$(OBJEXT)
cckdswap_OBJECTS = $(am_cckdswap_OBJECTS)
cckdswap_DEPENDENCIES = $(am__DEPENDENCIES_3)
cckdswap_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(cckdswap_LDFLAGS) $(LDFLAGS) -o $@
am_dasdcat_OBJECTS = dasdcat.$(OBJEXT)
dasdcat_OBJECTS = $(am_dasdcat_OBJECTS)
dasdcat_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdcat_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdcat_LDFLAGS) $(LDFLAGS) -o $@
am_dasdconv_OBJECTS = dasdconv.$(OBJEXT)
dasdconv_OBJECTS = $(am_dasdconv_OBJECTS)
dasdconv_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdconv_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdconv_LDFLAGS) $(LDFLAGS) -o $@
am_dasdcopy_OBJECTS = dasdcopy.$(OBJEXT)
dasdcopy_OBJECTS = $(am_dasdcopy_OBJECTS)
dasdcopy_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdcopy_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdcopy_LDFLAGS) $(LDFLAGS) -o $@
am_dasdinit_OBJECTS = dasdinit.$(OBJEXT)
dasdinit_OBJECTS = $(am_dasdinit_OBJECTS)
dasdinit_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdinit_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdinit_LDFLAGS) $(LDFLAGS) -o $@
am_dasdisup_OBJECTS = dasdisup.$(OBJEXT)
dasdisup_OBJECTS = $(am_dasdisup_OBJECTS)
dasdisup_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdisup_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdisup_LDFLAGS) $(LDFLAGS) -o $@
am_dasdload_OBJECTS = dasdload.$(OBJEXT)
dasdload_OBJECTS = $(am_dasdload_OBJECTS)
dasdload_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdload_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdload_LDFLAGS) $(LDFLAGS) -o $@
am_zdasdload_OBJECTS = zdasdload.$(OBJEXT)
zdasdload_OBJECTS = $(am_zdasdload_OBJECTS)
zdasdload_DEPENDENCIES = $(am__DEPENDENCIES_3)
zdasdload_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdload_LDFLAGS) $(LDFLAGS) -o $@
am_dasdls_OBJECTS = dasdls.$(OBJEXT)
dasdls_OBJECTS = $(am_dasdls_OBJECTS)
dasdls_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdls_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdls_LDFLAGS) $(LDFLAGS) -o $@
am_dasdpdsu_OBJECTS = dasdpdsu.$(OBJEXT)
dasdpdsu_OBJECTS = $(am_dasdpdsu_OBJECTS)
dasdpdsu_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdpdsu_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdpdsu_LDFLAGS) $(LDFLAGS) -o $@
am_dasdseq_OBJECTS = dasdseq.$(OBJEXT)
dasdseq_OBJECTS = $(am_dasdseq_OBJECTS)
dasdseq_DEPENDENCIES = $(am__DEPENDENCIES_3)
dasdseq_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dasdseq_LDFLAGS) $(LDFLAGS) -o $@
am_dmap2hrc_OBJECTS = dmap2hrc.$(OBJEXT)
dmap2hrc_OBJECTS = $(am_dmap2hrc_OBJECTS)
dmap2hrc_DEPENDENCIES = $(am__DEPENDENCIES_3)
dmap2hrc_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(dmap2hrc_LDFLAGS) $(LDFLAGS) -o $@
am__hercifc_SOURCES_DIST = hercifc.c
am_hercifc_OBJECTS = hercifc.$(OBJEXT)
hercifc_OBJECTS = $(am_hercifc_OBJECTS)
hercifc_DEPENDENCIES = $(am__DEPENDENCIES_3)
hercifc_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hercifc_LDFLAGS) $(LDFLAGS) -o $@
am__herclin_SOURCES_DIST = herclin.c hdlmain.c
am_herclin_OBJECTS = herclin.$(OBJEXT) \
	hdlmain.$(OBJEXT)
herclin_OBJECTS = $(am_herclin_OBJECTS)
herclin_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(herclin_LDFLAGS) $(LDFLAGS) -o $@
am_hercules_OBJECTS = bootstrap.$(OBJEXT) hdlmain.$(OBJEXT)
hercules_OBJECTS = $(am_hercules_OBJECTS)
hercules_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hercules_LDFLAGS) $(LDFLAGS) -o $@
am_hetget_OBJECTS = hetget.$(OBJEXT)
hetget_OBJECTS = $(am_hetget_OBJECTS)
hetget_DEPENDENCIES = $(am__DEPENDENCIES_3)
hetget_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hetget_LDFLAGS) $(LDFLAGS) -o $@
am_hetinit_OBJECTS = hetinit.$(OBJEXT)
hetinit_OBJECTS = $(am_hetinit_OBJECTS)
hetinit_DEPENDENCIES = $(am__DEPENDENCIES_3)
hetinit_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hetinit_LDFLAGS) $(LDFLAGS) -o $@
am_hetmap_OBJECTS = hetmap.$(OBJEXT)
hetmap_OBJECTS = $(am_hetmap_OBJECTS)
hetmap_DEPENDENCIES = $(am__DEPENDENCIES_3)
hetmap_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hetmap_LDFLAGS) $(LDFLAGS) -o $@
am_hetupd_OBJECTS = hetupd.$(OBJEXT)
hetupd_OBJECTS = $(am_hetupd_OBJECTS)
hetupd_DEPENDENCIES = $(am__DEPENDENCIES_3)
hetupd_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(hetupd_LDFLAGS) $(LDFLAGS) -o $@
am_tapecopy_OBJECTS = tapecopy.$(OBJEXT)
tapecopy_OBJECTS = $(am_tapecopy_OBJECTS)
tapecopy_DEPENDENCIES = $(am__DEPENDENCIES_3)
tapecopy_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(tapecopy_LDFLAGS) $(LDFLAGS) -o $@
am_tapemap_OBJECTS = tapemap.$(OBJEXT)
tapemap_OBJECTS = $(am_tapemap_OBJECTS)
tapemap_DEPENDENCIES = $(am__DEPENDENCIES_3)
tapemap_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(tapemap_LDFLAGS) $(LDFLAGS) -o $@
am_tapesplt_OBJECTS = tapesplt.$(OBJEXT)
tapesplt_OBJECTS = $(am_tapesplt_OBJECTS)
tapesplt_DEPENDENCIES = $(am__DEPENDENCIES_3)
tapesplt_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(tapesplt_LDFLAGS) $(LDFLAGS) -o $@
am_vmfplc2_OBJECTS = vmfplc2.$(OBJEXT)
vmfplc2_OBJECTS = $(am_vmfplc2_OBJECTS)
vmfplc2_DEPENDENCIES = $(am__DEPENDENCIES_3)
vmfplc2_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(vmfplc2_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/autoconf/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(dyngui_la_SOURCES) $(dyn75_la_SOURCES) $(dyninst_la_SOURCES) \
	$(hdt1052c_la_SOURCES) $(hdt1403_la_SOURCES) \
	$(hdt2703_la_SOURCES) $(hdt2880_la_SOURCES) \
	$(hdt3088_la_SOURCES) $(hdt3270_la_SOURCES) \
	$(hdt3420_la_SOURCES) $(hdt3505_la_SOURCES) \
	$(hdt3525_la_SOURCES) $(hdt3705_la_SOURCES) \
	$(hdteq_la_SOURCES) $(hdtptp_la_SOURCES) $(hdtqeth_la_SOURCES) \
	$(hdtzfcp_la_SOURCES) $(libherc_la_SOURCES) \
	$(EXTRA_libherc_la_SOURCES) $(libhercd_la_SOURCES) \
	$(libhercs_la_SOURCES) $(libherct_la_SOURCES) \
	$(libhercu_la_SOURCES) $(s37x_la_SOURCES) $(cckdcdsk_SOURCES) \
	$(cckdcomp_SOURCES) $(cckddiag_SOURCES) $(cckdswap_SOURCES) \
	$(dasdcat_SOURCES) $(dasdconv_SOURCES) $(dasdcopy_SOURCES) \
	$(dasdinit_SOURCES) $(dasdisup_SOURCES) $(dasdload_SOURCES) \
	$(dasdls_SOURCES) $(dasdpdsu_SOURCES) $(dasdseq_SOURCES) \
        $(zdasdload_SOURCES) \
	$(dmap2hrc_SOURCES) $(hercifc_SOURCES) $(herclin_SOURCES) \
	$(hercules_SOURCES) $(hetget_SOURCES) $(hetinit_SOURCES) \
	$(hetmap_SOURCES) $(hetupd_SOURCES) $(tapecopy_SOURCES) \
	$(tapemap_SOURCES) $(tapesplt_SOURCES) $(vmfplc2_SOURCES)
DIST_SOURCES = $(am__dyngui_la_SOURCES_DIST) \
	$(am__dyninst_la_SOURCES_DIST) $(am__hdt1052c_la_SOURCES_DIST) \
	$(am__hdt1403_la_SOURCES_DIST) $(am__hdt2703_la_SOURCES_DIST) \
	$(am__hdt2880_la_SOURCES_DIST) $(am__hdt3088_la_SOURCES_DIST) \
	$(am__hdt3270_la_SOURCES_DIST) $(am__hdt3420_la_SOURCES_DIST) \
	$(am__hdt3505_la_SOURCES_DIST) $(am__hdt3525_la_SOURCES_DIST) \
	$(am__hdt3705_la_SOURCES_DIST) $(am__hdteq_la_SOURCES_DIST) \
	$(am__hdtptp_la_SOURCES_DIST) $(am__hdtqeth_la_SOURCES_DIST) \
	$(am__hdtzfcp_la_SOURCES_DIST) $(am__libherc_la_SOURCES_DIST) \
	$(EXTRA_libherc_la_SOURCES) $(libhercd_la_SOURCES) \
	$(libhercs_la_SOURCES) $(libherct_la_SOURCES) \
	$(am__libhercu_la_SOURCES_DIST) $(am__s37x_la_SOURCES_DIST) \
	$(cckdcdsk_SOURCES) $(cckdcomp_SOURCES) $(cckddiag_SOURCES) \
	$(cckdswap_SOURCES) $(dasdcat_SOURCES) $(dasdconv_SOURCES) \
	$(dasdcopy_SOURCES) $(dasdinit_SOURCES) $(dasdisup_SOURCES) \
	$(dasdload_SOURCES) $(dasdls_SOURCES) $(dasdpdsu_SOURCES) \
	$(dasdseq_SOURCES) $(dmap2hrc_SOURCES) $(zdasdload_SOURCES)\
	$(am__hercifc_SOURCES_DIST) $(am__herclin_SOURCES_DIST) \
	$(hercules_SOURCES) $(hetget_SOURCES) $(hetinit_SOURCES) \
	$(hetmap_SOURCES) $(hetupd_SOURCES) $(tapecopy_SOURCES) \
	$(tapemap_SOURCES) $(tapesplt_SOURCES) $(vmfplc2_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(noinst_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = aclocal-1.13
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AS = as
AUTOCONF = autoconf
AUTOHEADER = autoheader
AUTOMAKE = automake-1.13
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS =  -W -Wall  -O3 -march=native -m128bit-long-double -minline-stringops-dynamically -fomit-frame-pointer
CPP = gcc -E
CPPFLAGS =  -DPKGDATADIR=\"$(pkgdatadir)\" -DMODULESDIR=\"$(modexecdir)\"
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = dlltool
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = 
FFLAGS = 
GREP = /usr/bin/grep
HERCIFC_GROUPNAME = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS =  -Wl,--warn-common
LIBADD_DL = -ldl
LIBOBJS = 
LIBS = -lrt -lz -lresolv -lnsl -lm -ldl  -pthread -lbz2
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = autoconf/ltmain.sh
LN_S = ln -s
LTLIBOBJS = 
MAINT = #
MAKEINFO = makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJDUMP = objdump
OBJEXT = o
PACKAGE = hercules
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 4.00
abs_builddir = /home/rahim/rahim/sandhawk
abs_srcdir = /home/rahim/rahim/sandhawk
abs_top_builddir = /home/rahim/rahim/sandhawk
abs_top_srcdir = /home/rahim/rahim/sandhawk
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/rahim/rahim/sandhawk/autoconf/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
modexecdir = $(libdir)/$(PACKAGE)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-unknown-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = unknown
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign 1.5
ACLOCAL_AMFLAGS = -I m4 -I autoconf
lns = ln -s
SUBDIRS = decNumber m4 util html man . crypto
LDADD = -lrt -lz -lresolv -lnsl -lm -ldl  -pthread -lbz2
AM_CPPFLAGS = -I$(top_srcdir) -I$(top_srcdir)/decNumber
#HERCIFC = 
HERCIFC = hercifc
#HERCLIN = 
HERCLIN = herclin
fthreads_SRC = fthreads.c
fishio_SRC = w32chan.c
FTHREADS = 
#FTHREADS = $(fthreads_SRC)
FISHIO = 
#FISHIO = $(fishio_SRC)

# We need to still include the source for the dynamic modules
# in with the distribution regardless of whether or not the dyanmic
# modules themselves are to be built so if dynamic load not possible,
# then we need to include the source on the EXTRA_hercules_SOURCES
# statement so even though they won't/don't actually get built, they
# still nonetheless get included into distribution tarball. This is
# *similar* to (bit not identical to) the way the fthreads sources
# are handled. With the fthreads sources though, they can at least always
# be built (even though they may not always generate any actual code
# whenever they do) whereas the dynamic module source CANNOT (MUST not)
# even be *attempted* to be "built" if support for building dynamic modules
# doesn't even exist on the system doing the building.
dynamic_SRC = dyngui.c   \
                     dyninst.c  \
                     s37x.c     \
                     s37xmod.c  \
                     hdteq.c

dyndev_SRC = commadpt.c  \
                     comm3705.c  \
                     console.c   \
                     cardpch.c   \
                     cardrdr.c   \
                     sockdev.c   \
                     printer.c   \
                     tapedev.c   \
                     tapeccws.c  \
                     sllib.c     \
                     hetlib.c    \
                     ftlib.c     \
                     awstape.c   \
                     faketape.c  \
                     hettape.c   \
                     omatape.c   \
                     scsitape.c  \
                     w32stape.c  \
                     ctc_ptp.c   \
                     ctc_lcs.c   \
                     ctc_ctci.c  \
                     ctcadpt.c   \
                     w32ctca.c   \
                     hchan.c     \
                     tuntap.c    \
                     resolve.c   \
                     qeth.c      \
                     mpc.c       \
                     zfcp.c      \
                     con1052c.c

#XSTATIC = -static

# -module         : create a dlopen'able module
# -no-undefined   : required on all platform that do not allow shared modules
#                   to have undefined symbols
# $(LDADD)        : Misc Linker flags set by autoconf
# -export-dynamic : so dlsym works (to be verified - not sure it is necessary)
# -avoid-version  : needed.. Otherwise libtool gives crazy names to Windows
#                   DLLs
#
XSTATIC = 
#DYNSRC = $(dyndev_SRC)
DYNSRC = 
#LTDL = 
LTDL = ltdl.c
#DYNMOD_LD_FLAGS = 
DYNMOD_LD_FLAGS = -module         \
                   -no-undefined    \
                   $(XSTATIC)       \
                   -export-dynamic  \
                   -avoid-version

#DYNMOD_LD_ADD = 
DYNMOD_LD_ADD = libherc.la    \
                   libhercs.la    \
                   libhercu.la    \
                   $(LDADD)

#LIB_LD_FLAGS = $(XSTATIC)    \
#                   -no-undefined  \
#                   -avoid-version

LIB_LD_FLAGS = -export-dynamic  \
                   $(XSTATIC)        \
                   -no-undefined     \
                   -avoid-version


#
# List of Libtool shared libraries & loadable modules
#
HERCLIBS = 
HERCLIBS2 = libhercs.la  \
              libhercu.la \
              libherct.la \
              libhercd.la \
              libherc.la

HERCMODS = dyngui.la   \
             dyninst.la  \
             dyn75.la  \
             s37x.la     \
             hdteq.la    \
             hdt1403.la  \
             hdt2703.la  \
             hdt3705.la  \
             hdt3088.la  \
             hdt3270.la  \
             hdt3420.la  \
             hdt3505.la  \
             hdt2880.la  \
             hdt3525.la  \
             hdtqeth.la  \
             hdtzfcp.la  \
             hdt1052c.la \
             hdtptp.la

modexec_LTLIBRARIES = $(HERCMODS)
noinst_LTLIBRARIES = $(HERCLIBS)
lib_LTLIBRARIES = $(HERCLIBS2)

#
# For each module:
#
#   ModuleName_la_SOURCES      = <list of source files>
#   ModuleName_la_LDFLAGS      = $(DYNMOD_LD_FLAGS) (see above)
#   ModuleName_la_LIBADD       = libherc.la (the Core Hercules Shared Library)
#   ModuleName_la_DEPENDENCIES = libherc.la (may not be necessary)
#
dyngui_la_SOURCES = dyngui.c
dyngui_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
dyngui_la_LIBADD = $(DYNMOD_LD_ADD)
dyninst_la_SOURCES = dyninst.c
dyninst_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
dyninst_la_LIBADD = $(DYNMOD_LD_ADD)
dyn75_la_SOURCES = dyn75.c tcpip.c
dyn75_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
dyn75_la_LIBADD = $(DYNMOD_LD_ADD)
s37x_la_SOURCES = s37x.c s37xmod.c
s37x_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
s37x_la_LIBADD = $(DYNMOD_LD_ADD)
hdteq_la_SOURCES = hdteq.c
hdteq_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdteq_la_LIBADD = $(DYNMOD_LD_ADD)
hdt1403_la_SOURCES = printer.c sockdev.c
hdt1403_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt1403_la_LIBADD = $(DYNMOD_LD_ADD)
hdt2880_la_SOURCES = hchan.c
hdt2880_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt2880_la_LIBADD = $(DYNMOD_LD_ADD)
hdt2703_la_SOURCES = commadpt.c
hdt2703_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt2703_la_LIBADD = $(DYNMOD_LD_ADD)
hdt3705_la_SOURCES = comm3705.c
hdt3705_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt3705_la_LIBADD = $(DYNMOD_LD_ADD)
hdt3088_la_SOURCES = ctc_lcs.c ctc_ctci.c ctcadpt.c w32ctca.c tuntap.c
hdt3088_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt3088_la_LIBADD = $(DYNMOD_LD_ADD)
hdt3270_la_SOURCES = console.c
hdt3270_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt3270_la_LIBADD = $(DYNMOD_LD_ADD)
hdt3420_la_SOURCES = tapedev.c tapeccws.c awstape.c faketape.c hettape.c omatape.c scsitape.c w32stape.c
hdt3420_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt3420_la_LIBADD = $(DYNMOD_LD_ADD) libherct.la
hdt3505_la_SOURCES = cardrdr.c sockdev.c
hdt3505_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt3505_la_LIBADD = $(DYNMOD_LD_ADD)
hdt3525_la_SOURCES = cardpch.c
hdt3525_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt3525_la_LIBADD = $(DYNMOD_LD_ADD)
hdtqeth_la_SOURCES = qeth.c mpc.c tuntap.c
hdtqeth_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdtqeth_la_LIBADD = $(DYNMOD_LD_ADD)
hdtzfcp_la_SOURCES = zfcp.c
hdtzfcp_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdtzfcp_la_LIBADD = $(DYNMOD_LD_ADD)
hdt1052c_la_SOURCES = con1052c.c
hdt1052c_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdt1052c_la_LIBADD = $(DYNMOD_LD_ADD)
hdtptp_la_SOURCES = ctc_ptp.c mpc.c resolve.c w32ctca.c tuntap.c
hdtptp_la_LDFLAGS = $(DYNMOD_LD_FLAGS)
hdtptp_la_LIBADD = $(DYNMOD_LD_ADD)

#
# Common data areas (shared) library
#
libhercs_la_SOURCES = hsys.c
libhercs_la_LDFLAGS = $(LIB_LD_FLAGS)
libhercs_la_LIBADD = $(LDADD)

#
# Tape utility subroutines (shared) library
#
libherct_la_SOURCES = sllib.c  \
                        ftlib.c  \
                        hetlib.c

libherct_la_LDFLAGS = $(LIB_LD_FLAGS)
libherct_la_LIBADD = $(LDADD) libhercs.la libhercu.la

#
# DASD utility subroutines (shared) library
#
libhercd_la_SOURCES = ckddasd.c   \
                        fbadasd.c   \
                        cckddasd.c  \
                        cckdutil.c  \
                        dasdtab.c   \
                        cache.c     \
                        dasdutil.c  \
                        shared.c

libhercd_la_LDFLAGS = $(LIB_LD_FLAGS)
libhercd_la_LIBADD = $(LDADD) libhercs.la libhercu.la

#
#
libhercu_la_SOURCES = version.c    \
                        hscutl.c     \
                        hscutl2.c    \
                        codepage.c   \
                        logger.c     \
                        logmsg.c     \
                        hdl.c        \
                        hostinfo.c   \
                        hsocket.c    \
                        memrchr.c    \
                        parser.c     \
                        pttrace.c    \
                        $(FTHREADS)  \
                        $(LTDL)

libhercu_la_LDFLAGS = $(LIB_LD_FLAGS)
libhercu_la_LIBADD = $(LDADD) libhercs.la

#
# Core Hercules (shared) library
#
libherc_la_SOURCES = hconsole.c   \
                       w32util.c    \
                       strsignal.c  \
                       impl.c       \
                       config.c     \
                       bldcfg.c     \
                       script.c     \
                       archlvl.c    \
                       panel.c      \
                       history.c    \
                       fillfnam.c   \
                       ipl.c        \
                       assist.c     \
                       dat.c        \
                       stack.c      \
                       cpu.c        \
                       vstore.c     \
                       general1.c   \
                       general2.c   \
                       general3.c   \
                       pfpo.c       \
                       plo.c        \
                       control.c    \
                       crypto.c     \
                       io.c         \
                       decimal.c    \
                       service.c    \
                       scedasd.c    \
                       scescsi.c    \
                       losc.c       \
                       chsc.c       \
                       opcode.c     \
                       diagnose.c   \
                       diagmssf.c   \
                       vm.c         \
                       vmd250.c     \
                       hdiagf18.c   \
                       dyn76.c      \
                       channel.c    \
                       external.c   \
                       float.c      \
                       trace.c      \
                       machchk.c    \
                       vector.c     \
                       xstore.c     \
                       cmpsc.c      \
                       sie.c        \
                       qdio.c       \
                       clock.c      \
                       timer.c      \
                       esame.c      \
                       ieee.c       \
                       SoftFloat.c  \
                       dfp.c        \
                       machdep.h    \
                       httpserv.c   \
                       cgibin.c     \
                       loadmem.c    \
                       loadparm.c   \
                       hsccmd.c     \
                       hscemode.c   \
                       hscpufun.c   \
                       hscloc.c     \
                       cmdtab.c     \
                       hao.c        \
                       hscmisc.c    \
                       sr.c         \
                       $(FISHIO)    \
                       $(DYNSRC)    \
                       ecpsvm.c     \
                       hRexx.c      \
                       hRexx_o.c    \
                       hRexx_r.c

EXTRA_libherc_la_SOURCES = $(fthreads_SRC)  \
                             $(fishio_SRC)    \
                             memrchr.c        \
                             $(dynamic_SRC)   \
                             $(extra_SRC)     \
                             $(dyndev_SRC)    \
                             ltdl.c

libherc_la_LDFLAGS = $(LIB_LD_FLAGS)
libherc_la_LIBADD = libhercs.la     \
                      libhercu.la     \
                      libherct.la     \
                      libhercd.la     \
                      decNumber/libdecNumber.la \
                      $(LDADD)

#HLDFLAGS = -dlopen self         \
#             -dlopen dyngui.la    \
#             -dlopen dyninst.la   \
#             -dlopen s37x.la      \
#             -dlopen hdteq.la     \
#             -dlopen hdt1403.la   \
#             -dlopen hdt3420.la   \
#             -dlopen hdt2703.la   \
#             -dlopen hdt3705.la   \
#             -dlopen hdt3088.la   \
#             -dlopen hdt3270.la   \
#             -dlopen hdt3505.la   \
#             -dlopen hdt3525.la   \
#             -dlopen hdtqeth.la   \
#             -dlopen hdtzfcp.la   \
#             -dlopen hdt1052c.la  \
#             -dlopen hdtptp.la


#
# THIS is the hercules executable.
#      hdlmain.c is requires so that dlopen(self) retrieves
#                the 'main' hdl symbols
#
HLDFLAGS = -dlopen self
#HLDFLAGS = 
#HDEPS = dyngui.la    \
#             dyninst.la   \
#             s37x.la      \
#             hdteq.la     \
#             hdt1403.la   \
#             hdt3420.la   \
#             hdt2703.la   \
#             hdt3705.la   \
#             hdt3088.la   \
#             hdt3270.la   \
#             hdt3505.la   \
#             hdt3525.la   \
#             hdtqeth.la   \
#             hdtzfcp.la   \
#             hdt1052c.la  \
#             hdtptp.la    \
#             libherc.la   \
#             libherct.la  \
#             libhercd.la

HDEPS = 
#HDEPS = 
hercules_SOURCES = bootstrap.c  \
                          hdlmain.c

hercules_LDADD = libherc.la libhercs.la $(LDADD)
hercules_LDFLAGS = $(HLDFLAGS)
hercules_DEPENDENCIES = libherc.la libhercs.la $(HDEPS)
herclin_SOURCES = herclin.c hdlmain.c
herclin_LDADD = libherc.la libhercs.la $(LDADD)
herclin_LDFLAGS = $(HLDFLAGS)
herclin_DEPENDENCIES = libherc.la libhercs.la $(HDEPS)

#
# side binaries
#
tools_LD_FLAGS = 
#tools_ADDLIBS = $(HERCLIBS2) $(LDADD) hdlmain.o
tools_ADDLIBS = $(HERCLIBS2) $(LDADD)
hercifc_SOURCES = hercifc.c
hercifc_LDADD = $(tools_ADDLIBS)
hercifc_LDFLAGS = $(tools_LD_FLAGS)
dasdinit_SOURCES = dasdinit.c
dasdinit_LDADD = $(tools_ADDLIBS)
dasdinit_LDFLAGS = $(tools_LD_FLAGS)
dasdisup_SOURCES = dasdisup.c
dasdisup_LDADD = $(tools_ADDLIBS)
dasdisup_LDFLAGS = $(tools_LD_FLAGS)
dasdload_SOURCES = dasdload.c
dasdload_LDADD = $(tools_ADDLIBS)
dasdload_LDFLAGS = $(tools_LD_FLAGS)
zdasdload_SOURCES = zdasdload.c
zdasdload_LDADD = $(tools_ADDLIBS)
zdasdload_LDFLAGS = $(tools_LD_FLAGS)
dasdconv_SOURCES = dasdconv.c
dasdconv_LDADD = $(tools_ADDLIBS)
dasdconv_LDFLAGS = $(tools_LD_FLAGS)
dasdls_SOURCES = dasdls.c
dasdls_LDADD = $(tools_ADDLIBS)
dasdls_LDFLAGS = $(tools_LD_FLAGS)
dasdcat_SOURCES = dasdcat.c
dasdcat_LDADD = $(tools_ADDLIBS)
dasdcat_LDFLAGS = $(tools_LD_FLAGS)
dasdpdsu_SOURCES = dasdpdsu.c
dasdpdsu_LDADD = $(tools_ADDLIBS)
dasdpdsu_LDFLAGS = $(tools_LD_FLAGS)
dasdseq_SOURCES = dasdseq.c
dasdseq_LDADD = $(tools_ADDLIBS)
dasdseq_LDFLAGS = $(tools_LD_FLAGS)
tapecopy_SOURCES = tapecopy.c
tapecopy_LDADD = $(tools_ADDLIBS)
tapecopy_LDFLAGS = $(tools_LD_FLAGS)
tapemap_SOURCES = tapemap.c
tapemap_LDADD = $(tools_ADDLIBS)
tapemap_LDFLAGS = $(tools_LD_FLAGS)
tapesplt_SOURCES = tapesplt.c
tapesplt_LDADD = $(tools_ADDLIBS)
tapesplt_LDFLAGS = $(tools_LD_FLAGS)
cckdcdsk_SOURCES = cckdcdsk.c
cckdcdsk_LDADD = $(tools_ADDLIBS)
cckdcdsk_LDFLAGS = $(tools_LD_FLAGS)
cckdcomp_SOURCES = cckdcomp.c
cckdcomp_LDADD = $(tools_ADDLIBS)
cckdcomp_LDFLAGS = $(tools_LD_FLAGS)
cckddiag_SOURCES = cckddiag.c
cckddiag_LDADD = $(tools_ADDLIBS)
cckddiag_LDFLAGS = $(tools_LD_FLAGS)
dasdcopy_SOURCES = dasdcopy.c
dasdcopy_LDADD = $(tools_ADDLIBS)
dasdcopy_LDFLAGS = $(tools_LD_FLAGS)
cckdswap_SOURCES = cckdswap.c
cckdswap_LDADD = $(tools_ADDLIBS)
cckdswap_LDFLAGS = $(tools_LD_FLAGS)
hetget_SOURCES = hetget.c
hetget_LDADD = $(tools_ADDLIBS)
hetget_LDFLAGS = $(tools_LD_FLAGS)
hetinit_SOURCES = hetinit.c
hetinit_LDADD = $(tools_ADDLIBS)
hetinit_LDFLAGS = $(tools_LD_FLAGS)
hetmap_SOURCES = hetmap.c
hetmap_LDADD = $(tools_ADDLIBS)
hetmap_LDFLAGS = $(tools_LD_FLAGS)
hetupd_SOURCES = hetupd.c
hetupd_LDADD = $(tools_ADDLIBS)
hetupd_LDFLAGS = $(tools_LD_FLAGS)
dmap2hrc_SOURCES = dmap2hrc.c
dmap2hrc_LDADD = $(tools_ADDLIBS)
dmap2hrc_LDFLAGS = $(tools_LD_FLAGS)
vmfplc2_SOURCES = vmfplc2.c
vmfplc2_LDADD = $(tools_ADDLIBS)
vmfplc2_LDFLAGS = $(tools_LD_FLAGS)
#
# files that are not 'built' per-se
#
#
# Also contains some WIN32 only source files
#
EXTRA_DIST = autoconf/config.rpath \
             autoconf/mkinstalldirs \
             COPYRIGHT             \
             hercules.cnf          \
             cckdfix.c             \
             license_dyn76.txt     \
             README.COMMADPT       \
             README.SVN            \
             README.DYNMOD         \
             README.ECPSVM         \
             README.HAO            \
             README.HDL            \
             README.IOARCH         \
             README.ISSUES         \
             README.MINGW          \
             README.NETWORKING     \
             README.OSX            \
             README.TAPE           \
             README.HERCLOGO       \
             CHANGES               \
             RELEASE.NOTES         \
             README.MSVC           \
             README.SUN            \
             README.AIX            \
             _TODO.txt             \
             makefile.msvc         \
             makefile-dllmod.msvc  \
             msvc.makefile.includes/BZIP2_DIR.msvc    \
             msvc.makefile.includes/BZIP2_FLAGS.msvc  \
             msvc.makefile.includes/BZIP2_RULES.msvc  \
             msvc.makefile.includes/CONFIG.msvc       \
             msvc.makefile.includes/DEBUG_RETAIL.msvc \
             msvc.makefile.includes/HERC_FLAGS.msvc   \
             msvc.makefile.includes/MOD_RULES1.msvc   \
             msvc.makefile.includes/MOD_RULES2.msvc   \
             msvc.makefile.includes/MODULES.msvc      \
             msvc.makefile.includes/OBJ_CODE.msvc     \
             msvc.makefile.includes/OUTDIR_RULES.msvc \
             msvc.makefile.includes/OUTPUT_DIRS.msvc  \
             msvc.makefile.includes/PCRE_DIR.msvc     \
             msvc.makefile.includes/PCRE_FLAGS.msvc   \
             msvc.makefile.includes/PCRE_RULES.msvc   \
             msvc.makefile.includes/PRIM_RULES.msvc   \
             msvc.makefile.includes/REXX_DIRS.msvc     \
             msvc.makefile.includes/REXX_FLAGS.msvc   \
             msvc.makefile.includes/REXX_RULES.msvc   \
             msvc.makefile.includes/VERSION.msvc      \
             msvc.makefile.includes/ZLIB_DIR.msvc     \
             msvc.makefile.includes/ZLIB_FLAGS.msvc   \
             msvc.makefile.includes/ZLIB_RULES.msvc   \
             makefile.bat          \
             dynmake.bat           \
             Hercules.dsp          \
             Hercules.dsw          \
             Hercules.vcproj       \
             Hercules.sln          \
             hercver.rc            \
             build_pch.c           \
             conspawn.c            \
             getopt.c              \
             wthreads.c            \
             herclogo.txt          \
             hercules.ico


#
# Source Header files. No 'build' for those
#
noinst_HEADERS = hostinfo.h     \
                 cpuint.h       \
                 feat370.h      \
                 feat390.h      \
                 m38tcp.h       \
                 feat900.h      \
                 featall.h      \
                 featchk.h      \
                 feature.h      \
                 esa390.h       \
                 opcode.h       \
                 clock.h        \
                 hercules.h     \
                 hinlines.h     \
                 inline.h       \
                 dat.h          \
                 vstore.h       \
                 hbyteswp.h     \
                 dasdblks.h     \
                 hetlib.h       \
                 ftlib.h        \
                 version.h      \
                 parser.h       \
                 dasdtab.h      \
                 sllib.h        \
                 htypes.h       \
                 fthreads.h     \
                 w32chan.h      \
                 w32ctca.h      \
                 tt32api.h      \
                 resolve.h      \
                 ctc_ptp.h      \
                 linklist.h     \
                 httpmisc.h     \
                 devtype.h      \
                 codepage.h     \
                 ctcadpt.h      \
                 hercifc.h      \
                 tuntap.h       \
                 tapedev.h      \
                 scsitape.h     \
                 logger.h       \
                 commadpt.h     \
                 comm3705.h     \
                 cnsllogo.h     \
                 cache.h        \
                 ecpsvm.h       \
                 memrchr.h      \
                 shared.h       \
                 hscutl.h       \
                 cmdtab.h       \
                 hdl.h          \
                 sockdev.h      \
                 ltdl.h         \
                 herc_getopt.h  \
                 service.h      \
                 chsc.h         \
                 qeth.h         \
                 qdio.h         \
                 zfcp.h         \
                 mpc.h          \
                 pttrace.h      \
                 history.h      \
                 sr.h           \
                 hchan.h        \
                 fillfnam.h     \
                 hthreads.h     \
                 hostopts.h     \
                 w32util.h      \
                 hconsts.h      \
                 herror.h       \
                 hmacros.h      \
                 hstructs.h     \
                 hexterns.h     \
                 hconsole.h     \
                 hextapi.h      \
                 hstdinc.h      \
                 ccfixme.h      \
                 ccnowarn.h     \
                 hstdint.h      \
                 hsocket.h      \
                 w32stape.h     \
                 w32dl.h        \
                 hercwind.h     \
                 getopt.h       \
                 w32mtio.h      \
                 vmd250.h       \
                 msgenu.h       \
                 wthreads.h     \
                 hdiagf18.h     \
                 dbgtrace.h     \
                 chain.h        \
                 extstring.h    \
                 hRexx.h        \
                 hRexxapi.h     \
                 $(extra_dynamic_SRC)

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in: # $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

install-modexecLTLIBRARIES: $(modexec_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(modexec_LTLIBRARIES)'; test -n "$(modexecdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(modexecdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(modexecdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(modexecdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(modexecdir)"; \
	}

uninstall-modexecLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(modexec_LTLIBRARIES)'; test -n "$(modexecdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(modexecdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(modexecdir)/$$f"; \
	done

clean-modexecLTLIBRARIES:
	-test -z "$(modexec_LTLIBRARIES)" || rm -f $(modexec_LTLIBRARIES)
	@list='$(modexec_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)
	@list='$(noinst_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

dyngui.la: $(dyngui_la_OBJECTS) $(dyngui_la_DEPENDENCIES) $(EXTRA_dyngui_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(dyngui_la_LINK) $(am_dyngui_la_rpath) $(dyngui_la_OBJECTS) $(dyngui_la_LIBADD) $(LIBS)

dyninst.la: $(dyninst_la_OBJECTS) $(dyninst_la_DEPENDENCIES) $(EXTRA_dyninst_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(dyninst_la_LINK) $(am_dyninst_la_rpath) $(dyninst_la_OBJECTS) $(dyninst_la_LIBADD) $(LIBS)

dyn75.la: $(dyn75_la_OBJECTS) $(dyn75_la_DEPENDENCIES) $(EXTRA_dyn75_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(dyn75_la_LINK) $(am_dyn75_la_rpath) $(dyn75_la_OBJECTS) $(dyn75_la_LIBADD) $(LIBS)

hdt1052c.la: $(hdt1052c_la_OBJECTS) $(hdt1052c_la_DEPENDENCIES) $(EXTRA_hdt1052c_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt1052c_la_LINK) $(am_hdt1052c_la_rpath) $(hdt1052c_la_OBJECTS) $(hdt1052c_la_LIBADD) $(LIBS)

hdt1403.la: $(hdt1403_la_OBJECTS) $(hdt1403_la_DEPENDENCIES) $(EXTRA_hdt1403_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt1403_la_LINK) $(am_hdt1403_la_rpath) $(hdt1403_la_OBJECTS) $(hdt1403_la_LIBADD) $(LIBS)

hdt2703.la: $(hdt2703_la_OBJECTS) $(hdt2703_la_DEPENDENCIES) $(EXTRA_hdt2703_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt2703_la_LINK) $(am_hdt2703_la_rpath) $(hdt2703_la_OBJECTS) $(hdt2703_la_LIBADD) $(LIBS)

hdt2880.la: $(hdt2880_la_OBJECTS) $(hdt2880_la_DEPENDENCIES) $(EXTRA_hdt2880_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt2880_la_LINK) $(am_hdt2880_la_rpath) $(hdt2880_la_OBJECTS) $(hdt2880_la_LIBADD) $(LIBS)

hdt3088.la: $(hdt3088_la_OBJECTS) $(hdt3088_la_DEPENDENCIES) $(EXTRA_hdt3088_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt3088_la_LINK) $(am_hdt3088_la_rpath) $(hdt3088_la_OBJECTS) $(hdt3088_la_LIBADD) $(LIBS)

hdt3270.la: $(hdt3270_la_OBJECTS) $(hdt3270_la_DEPENDENCIES) $(EXTRA_hdt3270_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt3270_la_LINK) $(am_hdt3270_la_rpath) $(hdt3270_la_OBJECTS) $(hdt3270_la_LIBADD) $(LIBS)

hdt3420.la: $(hdt3420_la_OBJECTS) $(hdt3420_la_DEPENDENCIES) $(EXTRA_hdt3420_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt3420_la_LINK) $(am_hdt3420_la_rpath) $(hdt3420_la_OBJECTS) $(hdt3420_la_LIBADD) $(LIBS)

hdt3505.la: $(hdt3505_la_OBJECTS) $(hdt3505_la_DEPENDENCIES) $(EXTRA_hdt3505_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt3505_la_LINK) $(am_hdt3505_la_rpath) $(hdt3505_la_OBJECTS) $(hdt3505_la_LIBADD) $(LIBS)

hdt3525.la: $(hdt3525_la_OBJECTS) $(hdt3525_la_DEPENDENCIES) $(EXTRA_hdt3525_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt3525_la_LINK) $(am_hdt3525_la_rpath) $(hdt3525_la_OBJECTS) $(hdt3525_la_LIBADD) $(LIBS)

hdt3705.la: $(hdt3705_la_OBJECTS) $(hdt3705_la_DEPENDENCIES) $(EXTRA_hdt3705_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdt3705_la_LINK) $(am_hdt3705_la_rpath) $(hdt3705_la_OBJECTS) $(hdt3705_la_LIBADD) $(LIBS)

hdteq.la: $(hdteq_la_OBJECTS) $(hdteq_la_DEPENDENCIES) $(EXTRA_hdteq_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdteq_la_LINK) $(am_hdteq_la_rpath) $(hdteq_la_OBJECTS) $(hdteq_la_LIBADD) $(LIBS)

hdtptp.la: $(hdtptp_la_OBJECTS) $(hdtptp_la_DEPENDENCIES) $(EXTRA_hdtptp_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdtptp_la_LINK) $(am_hdtptp_la_rpath) $(hdtptp_la_OBJECTS) $(hdtptp_la_LIBADD) $(LIBS)

hdtqeth.la: $(hdtqeth_la_OBJECTS) $(hdtqeth_la_DEPENDENCIES) $(EXTRA_hdtqeth_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdtqeth_la_LINK) $(am_hdtqeth_la_rpath) $(hdtqeth_la_OBJECTS) $(hdtqeth_la_LIBADD) $(LIBS)

hdtzfcp.la: $(hdtzfcp_la_OBJECTS) $(hdtzfcp_la_DEPENDENCIES) $(EXTRA_hdtzfcp_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(hdtzfcp_la_LINK) $(am_hdtzfcp_la_rpath) $(hdtzfcp_la_OBJECTS) $(hdtzfcp_la_LIBADD) $(LIBS)

libherc.la: $(libherc_la_OBJECTS) $(libherc_la_DEPENDENCIES) $(EXTRA_libherc_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libherc_la_LINK) -rpath $(libdir) $(libherc_la_OBJECTS) $(libherc_la_LIBADD) $(LIBS)

libhercd.la: $(libhercd_la_OBJECTS) $(libhercd_la_DEPENDENCIES) $(EXTRA_libhercd_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libhercd_la_LINK) -rpath $(libdir) $(libhercd_la_OBJECTS) $(libhercd_la_LIBADD) $(LIBS)

libhercs.la: $(libhercs_la_OBJECTS) $(libhercs_la_DEPENDENCIES) $(EXTRA_libhercs_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libhercs_la_LINK) -rpath $(libdir) $(libhercs_la_OBJECTS) $(libhercs_la_LIBADD) $(LIBS)

libherct.la: $(libherct_la_OBJECTS) $(libherct_la_DEPENDENCIES) $(EXTRA_libherct_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libherct_la_LINK) -rpath $(libdir) $(libherct_la_OBJECTS) $(libherct_la_LIBADD) $(LIBS)

libhercu.la: $(libhercu_la_OBJECTS) $(libhercu_la_DEPENDENCIES) $(EXTRA_libhercu_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libhercu_la_LINK) -rpath $(libdir) $(libhercu_la_OBJECTS) $(libhercu_la_LIBADD) $(LIBS)

s37x.la: $(s37x_la_OBJECTS) $(s37x_la_DEPENDENCIES) $(EXTRA_s37x_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(s37x_la_LINK) $(am_s37x_la_rpath) $(s37x_la_OBJECTS) $(s37x_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

cckdcdsk$(EXEEXT): $(cckdcdsk_OBJECTS) $(cckdcdsk_DEPENDENCIES) $(EXTRA_cckdcdsk_DEPENDENCIES) 
	@rm -f cckdcdsk$(EXEEXT)
	$(AM_V_CCLD)$(cckdcdsk_LINK) $(cckdcdsk_OBJECTS) $(cckdcdsk_LDADD) $(LIBS)

cckdcomp$(EXEEXT): $(cckdcomp_OBJECTS) $(cckdcomp_DEPENDENCIES) $(EXTRA_cckdcomp_DEPENDENCIES) 
	@rm -f cckdcomp$(EXEEXT)
	$(AM_V_CCLD)$(cckdcomp_LINK) $(cckdcomp_OBJECTS) $(cckdcomp_LDADD) $(LIBS)

cckddiag$(EXEEXT): $(cckddiag_OBJECTS) $(cckddiag_DEPENDENCIES) $(EXTRA_cckddiag_DEPENDENCIES) 
	@rm -f cckddiag$(EXEEXT)
	$(AM_V_CCLD)$(cckddiag_LINK) $(cckddiag_OBJECTS) $(cckddiag_LDADD) $(LIBS)

cckdswap$(EXEEXT): $(cckdswap_OBJECTS) $(cckdswap_DEPENDENCIES) $(EXTRA_cckdswap_DEPENDENCIES) 
	@rm -f cckdswap$(EXEEXT)
	$(AM_V_CCLD)$(cckdswap_LINK) $(cckdswap_OBJECTS) $(cckdswap_LDADD) $(LIBS)

dasdcat$(EXEEXT): $(dasdcat_OBJECTS) $(dasdcat_DEPENDENCIES) $(EXTRA_dasdcat_DEPENDENCIES) 
	@rm -f dasdcat$(EXEEXT)
	$(AM_V_CCLD)$(dasdcat_LINK) $(dasdcat_OBJECTS) $(dasdcat_LDADD) $(LIBS)

dasdconv$(EXEEXT): $(dasdconv_OBJECTS) $(dasdconv_DEPENDENCIES) $(EXTRA_dasdconv_DEPENDENCIES) 
	@rm -f dasdconv$(EXEEXT)
	$(AM_V_CCLD)$(dasdconv_LINK) $(dasdconv_OBJECTS) $(dasdconv_LDADD) $(LIBS)

dasdcopy$(EXEEXT): $(dasdcopy_OBJECTS) $(dasdcopy_DEPENDENCIES) $(EXTRA_dasdcopy_DEPENDENCIES) 
	@rm -f dasdcopy$(EXEEXT)
	$(AM_V_CCLD)$(dasdcopy_LINK) $(dasdcopy_OBJECTS) $(dasdcopy_LDADD) $(LIBS)

dasdinit$(EXEEXT): $(dasdinit_OBJECTS) $(dasdinit_DEPENDENCIES) $(EXTRA_dasdinit_DEPENDENCIES) 
	@rm -f dasdinit$(EXEEXT)
	$(AM_V_CCLD)$(dasdinit_LINK) $(dasdinit_OBJECTS) $(dasdinit_LDADD) $(LIBS)

dasdisup$(EXEEXT): $(dasdisup_OBJECTS) $(dasdisup_DEPENDENCIES) $(EXTRA_dasdisup_DEPENDENCIES) 
	@rm -f dasdisup$(EXEEXT)
	$(AM_V_CCLD)$(dasdisup_LINK) $(dasdisup_OBJECTS) $(dasdisup_LDADD) $(LIBS)

dasdload$(EXEEXT): $(dasdload_OBJECTS) $(dasdload_DEPENDENCIES) $(EXTRA_dasdload_DEPENDENCIES) 
	@rm -f dasdload$(EXEEXT)
	$(AM_V_CCLD)$(dasdload_LINK) $(dasdload_OBJECTS) $(dasdload_LDADD) $(LIBS)

zdasdload$(EXEEXT): $(zdasdload_OBJECTS) $(zdasdload_DEPENDENCIES) $(EXTRA_zdasdload_DEPENDENCIES) 
	@rm -f zdasdload$(EXEEXT)
	$(AM_V_CCLD)$(zdasdload_LINK) $(zdasdload_OBJECTS) $(zdasdload_LDADD) $(LIBS)

dasdls$(EXEEXT): $(dasdls_OBJECTS) $(dasdls_DEPENDENCIES) $(EXTRA_dasdls_DEPENDENCIES) 
	@rm -f dasdls$(EXEEXT)
	$(AM_V_CCLD)$(dasdls_LINK) $(dasdls_OBJECTS) $(dasdls_LDADD) $(LIBS)

dasdpdsu$(EXEEXT): $(dasdpdsu_OBJECTS) $(dasdpdsu_DEPENDENCIES) $(EXTRA_dasdpdsu_DEPENDENCIES) 
	@rm -f dasdpdsu$(EXEEXT)
	$(AM_V_CCLD)$(dasdpdsu_LINK) $(dasdpdsu_OBJECTS) $(dasdpdsu_LDADD) $(LIBS)

dasdseq$(EXEEXT): $(dasdseq_OBJECTS) $(dasdseq_DEPENDENCIES) $(EXTRA_dasdseq_DEPENDENCIES) 
	@rm -f dasdseq$(EXEEXT)
	$(AM_V_CCLD)$(dasdseq_LINK) $(dasdseq_OBJECTS) $(dasdseq_LDADD) $(LIBS)

dmap2hrc$(EXEEXT): $(dmap2hrc_OBJECTS) $(dmap2hrc_DEPENDENCIES) $(EXTRA_dmap2hrc_DEPENDENCIES) 
	@rm -f dmap2hrc$(EXEEXT)
	$(AM_V_CCLD)$(dmap2hrc_LINK) $(dmap2hrc_OBJECTS) $(dmap2hrc_LDADD) $(LIBS)

hercifc$(EXEEXT): $(hercifc_OBJECTS) $(hercifc_DEPENDENCIES) $(EXTRA_hercifc_DEPENDENCIES) 
	@rm -f hercifc$(EXEEXT)
	$(AM_V_CCLD)$(hercifc_LINK) $(hercifc_OBJECTS) $(hercifc_LDADD) $(LIBS)

herclin$(EXEEXT): $(herclin_OBJECTS) $(herclin_DEPENDENCIES) $(EXTRA_herclin_DEPENDENCIES) 
	@rm -f herclin$(EXEEXT)
	$(AM_V_CCLD)$(herclin_LINK) $(herclin_OBJECTS) $(herclin_LDADD) $(LIBS)

hercules$(EXEEXT): $(hercules_OBJECTS) $(hercules_DEPENDENCIES) $(EXTRA_hercules_DEPENDENCIES) 
	@rm -f hercules$(EXEEXT)
	$(AM_V_CCLD)$(hercules_LINK) $(hercules_OBJECTS) $(hercules_LDADD) $(LIBS)

hetget$(EXEEXT): $(hetget_OBJECTS) $(hetget_DEPENDENCIES) $(EXTRA_hetget_DEPENDENCIES) 
	@rm -f hetget$(EXEEXT)
	$(AM_V_CCLD)$(hetget_LINK) $(hetget_OBJECTS) $(hetget_LDADD) $(LIBS)

hetinit$(EXEEXT): $(hetinit_OBJECTS) $(hetinit_DEPENDENCIES) $(EXTRA_hetinit_DEPENDENCIES) 
	@rm -f hetinit$(EXEEXT)
	$(AM_V_CCLD)$(hetinit_LINK) $(hetinit_OBJECTS) $(hetinit_LDADD) $(LIBS)

hetmap$(EXEEXT): $(hetmap_OBJECTS) $(hetmap_DEPENDENCIES) $(EXTRA_hetmap_DEPENDENCIES) 
	@rm -f hetmap$(EXEEXT)
	$(AM_V_CCLD)$(hetmap_LINK) $(hetmap_OBJECTS) $(hetmap_LDADD) $(LIBS)

hetupd$(EXEEXT): $(hetupd_OBJECTS) $(hetupd_DEPENDENCIES) $(EXTRA_hetupd_DEPENDENCIES) 
	@rm -f hetupd$(EXEEXT)
	$(AM_V_CCLD)$(hetupd_LINK) $(hetupd_OBJECTS) $(hetupd_LDADD) $(LIBS)

tapecopy$(EXEEXT): $(tapecopy_OBJECTS) $(tapecopy_DEPENDENCIES) $(EXTRA_tapecopy_DEPENDENCIES) 
	@rm -f tapecopy$(EXEEXT)
	$(AM_V_CCLD)$(tapecopy_LINK) $(tapecopy_OBJECTS) $(tapecopy_LDADD) $(LIBS)

tapemap$(EXEEXT): $(tapemap_OBJECTS) $(tapemap_DEPENDENCIES) $(EXTRA_tapemap_DEPENDENCIES) 
	@rm -f tapemap$(EXEEXT)
	$(AM_V_CCLD)$(tapemap_LINK) $(tapemap_OBJECTS) $(tapemap_LDADD) $(LIBS)

tapesplt$(EXEEXT): $(tapesplt_OBJECTS) $(tapesplt_DEPENDENCIES) $(EXTRA_tapesplt_DEPENDENCIES) 
	@rm -f tapesplt$(EXEEXT)
	$(AM_V_CCLD)$(tapesplt_LINK) $(tapesplt_OBJECTS) $(tapesplt_LDADD) $(LIBS)

vmfplc2$(EXEEXT): $(vmfplc2_OBJECTS) $(vmfplc2_DEPENDENCIES) $(EXTRA_vmfplc2_DEPENDENCIES) 
	@rm -f vmfplc2$(EXEEXT)
	$(AM_V_CCLD)$(vmfplc2_LINK) $(vmfplc2_OBJECTS) $(vmfplc2_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/SoftFloat.Plo
include ./$(DEPDIR)/archlvl.Plo
include ./$(DEPDIR)/assist.Plo
include ./$(DEPDIR)/awstape.Plo
include ./$(DEPDIR)/bldcfg.Plo
include ./$(DEPDIR)/bootstrap.Po
include ./$(DEPDIR)/cache.Plo
include ./$(DEPDIR)/cardpch.Plo
include ./$(DEPDIR)/cardrdr.Plo
include ./$(DEPDIR)/cckdcdsk.Po
include ./$(DEPDIR)/cckdcomp.Po
include ./$(DEPDIR)/cckddasd.Plo
include ./$(DEPDIR)/cckddiag.Po
include ./$(DEPDIR)/cckdswap.Po
include ./$(DEPDIR)/cckdutil.Plo
include ./$(DEPDIR)/cgibin.Plo
include ./$(DEPDIR)/channel.Plo
include ./$(DEPDIR)/chsc.Plo
include ./$(DEPDIR)/ckddasd.Plo
include ./$(DEPDIR)/clock.Plo
include ./$(DEPDIR)/cmdtab.Plo
include ./$(DEPDIR)/cmpsc.Plo
include ./$(DEPDIR)/codepage.Plo
include ./$(DEPDIR)/comm3705.Plo
include ./$(DEPDIR)/commadpt.Plo
include ./$(DEPDIR)/con1052c.Plo
include ./$(DEPDIR)/config.Plo
include ./$(DEPDIR)/console.Plo
include ./$(DEPDIR)/control.Plo
include ./$(DEPDIR)/cpu.Plo
include ./$(DEPDIR)/crypto.Plo
include ./$(DEPDIR)/ctc_ctci.Plo
include ./$(DEPDIR)/ctc_lcs.Plo
include ./$(DEPDIR)/ctc_ptp.Plo
include ./$(DEPDIR)/ctcadpt.Plo
include ./$(DEPDIR)/dasdcat.Po
include ./$(DEPDIR)/dasdconv.Po
include ./$(DEPDIR)/dasdcopy.Po
include ./$(DEPDIR)/dasdinit.Po
include ./$(DEPDIR)/dasdisup.Po
include ./$(DEPDIR)/dasdload.Po
include ./$(DEPDIR)/dasdls.Po
include ./$(DEPDIR)/dasdpdsu.Po
include ./$(DEPDIR)/dasdseq.Po
include ./$(DEPDIR)/dasdtab.Plo
include ./$(DEPDIR)/dasdutil.Plo
include ./$(DEPDIR)/dat.Plo
include ./$(DEPDIR)/decimal.Plo
include ./$(DEPDIR)/dfp.Plo
include ./$(DEPDIR)/diagmssf.Plo
include ./$(DEPDIR)/diagnose.Plo
include ./$(DEPDIR)/dmap2hrc.Po
include ./$(DEPDIR)/dyn76.Plo
include ./$(DEPDIR)/dyngui.Plo
include ./$(DEPDIR)/dyninst.Plo
include ./$(DEPDIR)/ecpsvm.Plo
include ./$(DEPDIR)/esame.Plo
include ./$(DEPDIR)/external.Plo
include ./$(DEPDIR)/faketape.Plo
include ./$(DEPDIR)/fbadasd.Plo
include ./$(DEPDIR)/fillfnam.Plo
include ./$(DEPDIR)/float.Plo
include ./$(DEPDIR)/fthreads.Plo
include ./$(DEPDIR)/ftlib.Plo
include ./$(DEPDIR)/general1.Plo
include ./$(DEPDIR)/general2.Plo
include ./$(DEPDIR)/general3.Plo
include ./$(DEPDIR)/hRexx.Plo
include ./$(DEPDIR)/hRexx_o.Plo
include ./$(DEPDIR)/hRexx_r.Plo
include ./$(DEPDIR)/hao.Plo
include ./$(DEPDIR)/hchan.Plo
include ./$(DEPDIR)/hconsole.Plo
include ./$(DEPDIR)/hdiagf18.Plo
include ./$(DEPDIR)/hdl.Plo
include ./$(DEPDIR)/hdlmain.Po
include ./$(DEPDIR)/hdteq.Plo
include ./$(DEPDIR)/hercifc.Po
include ./$(DEPDIR)/herclin.Po
include ./$(DEPDIR)/hetget.Po
include ./$(DEPDIR)/hetinit.Po
include ./$(DEPDIR)/hetlib.Plo
include ./$(DEPDIR)/hetmap.Po
include ./$(DEPDIR)/hettape.Plo
include ./$(DEPDIR)/hetupd.Po
include ./$(DEPDIR)/history.Plo
include ./$(DEPDIR)/hostinfo.Plo
include ./$(DEPDIR)/hsccmd.Plo
include ./$(DEPDIR)/hscemode.Plo
include ./$(DEPDIR)/hscloc.Plo
include ./$(DEPDIR)/hscmisc.Plo
include ./$(DEPDIR)/hscpufun.Plo
include ./$(DEPDIR)/hscutl.Plo
include ./$(DEPDIR)/hscutl2.Plo
include ./$(DEPDIR)/hsocket.Plo
include ./$(DEPDIR)/hsys.Plo
include ./$(DEPDIR)/httpserv.Plo
include ./$(DEPDIR)/ieee.Plo
include ./$(DEPDIR)/impl.Plo
include ./$(DEPDIR)/io.Plo
include ./$(DEPDIR)/ipl.Plo
include ./$(DEPDIR)/loadmem.Plo
include ./$(DEPDIR)/loadparm.Plo
include ./$(DEPDIR)/logger.Plo
include ./$(DEPDIR)/logmsg.Plo
include ./$(DEPDIR)/losc.Plo
include ./$(DEPDIR)/ltdl.Plo
include ./$(DEPDIR)/machchk.Plo
include ./$(DEPDIR)/memrchr.Plo
include ./$(DEPDIR)/mpc.Plo
include ./$(DEPDIR)/omatape.Plo
include ./$(DEPDIR)/opcode.Plo
include ./$(DEPDIR)/panel.Plo
include ./$(DEPDIR)/parser.Plo
include ./$(DEPDIR)/pfpo.Plo
include ./$(DEPDIR)/plo.Plo
include ./$(DEPDIR)/printer.Plo
include ./$(DEPDIR)/pttrace.Plo
include ./$(DEPDIR)/qdio.Plo
include ./$(DEPDIR)/qeth.Plo
include ./$(DEPDIR)/resolve.Plo
include ./$(DEPDIR)/s37x.Plo
include ./$(DEPDIR)/s37xmod.Plo
include ./$(DEPDIR)/scedasd.Plo
include ./$(DEPDIR)/scescsi.Plo
include ./$(DEPDIR)/script.Plo
include ./$(DEPDIR)/scsitape.Plo
include ./$(DEPDIR)/service.Plo
include ./$(DEPDIR)/shared.Plo
include ./$(DEPDIR)/sie.Plo
include ./$(DEPDIR)/sllib.Plo
include ./$(DEPDIR)/sockdev.Plo
include ./$(DEPDIR)/sr.Plo
include ./$(DEPDIR)/stack.Plo
include ./$(DEPDIR)/strsignal.Plo
include ./$(DEPDIR)/tapeccws.Plo
include ./$(DEPDIR)/tapecopy.Po
include ./$(DEPDIR)/tapedev.Plo
include ./$(DEPDIR)/tapemap.Po
include ./$(DEPDIR)/tapesplt.Po
include ./$(DEPDIR)/timer.Plo
include ./$(DEPDIR)/trace.Plo
include ./$(DEPDIR)/tuntap.Plo
include ./$(DEPDIR)/vector.Plo
include ./$(DEPDIR)/version.Plo
include ./$(DEPDIR)/vm.Plo
include ./$(DEPDIR)/vmd250.Plo
include ./$(DEPDIR)/vmfplc2.Po
include ./$(DEPDIR)/vstore.Plo
include ./$(DEPDIR)/w32chan.Plo
include ./$(DEPDIR)/w32ctca.Plo
include ./$(DEPDIR)/w32stape.Plo
include ./$(DEPDIR)/w32util.Plo
include ./$(DEPDIR)/xstore.Plo
include ./$(DEPDIR)/zfcp.Plo

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(modexecdir)" "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-modexecLTLIBRARIES clean-noinstLTLIBRARIES \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS install-exec-local \
	install-libLTLIBRARIES install-modexecLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-local uninstall-modexecLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
.MAKE: $(am__recursive_targets) all install-am install-exec-am \
	install-strip uninstall-am

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-binPROGRAMS \
	clean-cscope clean-generic clean-libLTLIBRARIES clean-libtool \
	clean-modexecLTLIBRARIES clean-noinstLTLIBRARIES cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-hook install-exec-local \
	install-html install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-modexecLTLIBRARIES \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-hook \
	uninstall-libLTLIBRARIES uninstall-local \
	uninstall-modexecLTLIBRARIES


cckd: cckd2ckd$(EXEEXT)  \
      cckdcdsk$(EXEEXT)  \
      cckddiag$(EXEEXT)  \
      cckdcomp$(EXEEXT)  \
      cckdswap$(EXEEXT)  \
      dasdcopy$(EXEEXT)

#########################################################
#           B U I L D   R U L E S  . . .
#########################################################
#
#            ***  PROGRAMMING NOTE! ***
#
#  The tabs in the below statements ARE significant!
#  Not all make programs accept (handle correctly)
#  make files that use blanks instead of tabs in their
#  build rules. Thus in order to remain compatible
#  with older make programs the below build rules
#  MUST use *tabs* and NOT BLANKS!
#
#########################################################

tar: dist

install-exec-local:

install-exec-hook:
	rm -f $(DESTDIR)$(libdir)/libherc*.a
	rm -f $(DESTDIR)$(modexecdir)/dyn*.a
	rm -f $(DESTDIR)$(modexecdir)/hdt*.a
#	rm -f $(DESTDIR)$(libdir)/libherc*
#
# NOTE : symbolic links point to FINAL destination (not to staged install)
#
	rm -f $(DESTDIR)$(bindir)/fba2cfba$(EXEEXT)
	(cd $(DESTDIR)$(bindir); ln -s ./dasdcopy$(EXEEXT) fba2cfba$(EXEEXT))
	rm -f $(DESTDIR)$(bindir)/ckd2cckd$(EXEEXT)
	(cd $(DESTDIR)$(bindir); ln -s ./dasdcopy$(EXEEXT) ckd2cckd$(EXEEXT))
	rm -f $(DESTDIR)$(bindir)/cfba2fba$(EXEEXT)
	(cd $(DESTDIR)$(bindir); ln -s ./dasdcopy$(EXEEXT) cfba2fba$(EXEEXT))
	rm -f $(DESTDIR)$(bindir)/cckd2ckd$(EXEEXT)
	(cd $(DESTDIR)$(bindir); ln -s ./dasdcopy$(EXEEXT) cckd2ckd$(EXEEXT))
#	chown root $(DESTDIR)$(bindir)/hercifc
##	chgrp $(HERCIFC_GROUPNAME) $(DESTDIR)$(bindir)/hercifc
#	chmod 0750 $(DESTDIR)$(bindir)/hercifc
#	chmod +s   $(DESTDIR)$(bindir)/hercifc
#	rm                             hercifc

uninstall-local:

uninstall-hook:
	rm -f $(DESTDIR)$(bindir)/fba2cfba$(EXEEXT)
	rm -f $(DESTDIR)$(bindir)/ckd2cckd$(EXEEXT)
	rm -f $(DESTDIR)$(bindir)/cfba2fba$(EXEEXT)
	rm -f $(DESTDIR)$(bindir)/cckd2ckd$(EXEEXT)

%.s: %.c
	$(COMPILE) -S $<

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
